ncells:
    - 1000
    - 5000
    # - 10000

n_mutation_groups:
    - 5
    - 10
    - 15

mutation_group_sizes:
    - 100
    - 500
    - 1000


nclusters:
    - 5
    - 10
    - 15

coverage:
    - 0.02
    - 0.05
    - 0.1

fp: 0.001
fn: 0.001

missing_rate: 0

lambda: 0

k: 0

vaf_threshold: 0.05
read_threshold: 1

estimated_fp: 0.0018
estimated_fn: 0.16

nseeds: 5


sample_ids:
    - DG1134
    - SA039
    - SA1049
    - SA1052
    - SA1055
    - SA1093
    - SA1142
    - SA1181
    - SA1188
    - SA530
    - SA605
    - SA906a
    - DG1197
    - SA1035
    - SA1050
    - SA1053
    - SA1056
    - SA1096
    - SA1162
    - SA1182
    - SA1292
    - SA535
    - SA609
    - SA906b
    - OV2295
    - SA1047
    - SA1051
    - SA1054
    - SA1091
    # - SA1135
    - SA1180
    - SA1184
    - SA501
    - SA604
    - SA610
  